from .auth import router as auth_router
from .devices import router as devices_router
from .traffic import router as traffic_router
from .traffic_history import router as traffic_history_router
from .traffic_dashboard import router as traffic_dashboard_router
from .traffic_collector import router as traffic_collector_router
from .traffic_stats import router as traffic_stats_router
from .settings import router as settings_router
from .large_screen import router as large_screen_router
from .large_screen_templates import router as large_screen_templates_router
from .license import router as license_router
from .seed import router as seed_router
from .device_id import router as device_id_router
from .device_status import router as device_status_router
from .stream import router as stream_router
from .device_push import router as device_push_router
from .test_stream_routes import router as test_stream_router
