"""
FluxaVision 客流统计系统 - 大华 SDK 客流采集服务

设计目标：
1. 设备添加后自动开始采集，无需手动点击订阅。
2. 优先使用订阅回调获取客流数据，失败时自动回退到主动查询。
3. 设备断线后自动重连，并在重连成功后恢复采集。
4. 将大华设备的连接过程、订阅过程、查询过程完整打印到日志，便于排查。

当前支持的采集路径：
1. AttachVideoStatSummary
2. RealLoadPictureEx + EVENT_IVS_NUMBERSTAT
3. StartFindNumberStat / DoFindNumberStat 轮询查询
"""

import ctypes
import logging
import threading
import time
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)

_SDK_AVAILABLE = False

try:
    import importlib.util
    import os
    import sys
    import traceback
    import types

    # PyInstaller 打包后，将 _MEIPASS/NetSDK 加入 sys.path，
    # 同时确保 SDK_Struct.py 能用 __file__ 找到同级的 Libs/win64/ DLL。
    if getattr(sys, 'frozen', False):
        _meipass = getattr(sys, '_MEIPASS', None)
        if _meipass:
            _netsdk_pkg = os.path.join(_meipass, 'NetSDK')
            if os.path.isdir(_netsdk_pkg) and _netsdk_pkg not in sys.path:
                sys.path.insert(0, os.path.dirname(_netsdk_pkg))  # 让 import NetSDK 可以找到
            # DLL 目录加入 PATH，防止 LoadLibrary 找不到依赖 dll
            _dll_dir = os.path.join(_netsdk_pkg, 'Libs', 'win64')
            if os.path.isdir(_dll_dir):
                os.environ['PATH'] = _dll_dir + os.pathsep + os.environ.get('PATH', '')
                # Python 3.8+ 需要显式 add_dll_directory
                if hasattr(os, 'add_dll_directory'):
                    os.add_dll_directory(_dll_dir)

    def _load_netsdk():
        """手动加载大华 NetSDK，绕过 wheel 包的自引用导入问题。"""
        pkg_dir = None
        for path in sys.path:
            candidate = os.path.join(path, "NetSDK")
            if os.path.isdir(candidate) and os.path.exists(os.path.join(candidate, "NetSDK.py")):
                pkg_dir = candidate
                break

        if not pkg_dir:
            raise ImportError("NetSDK package not found in sys.path")

        init_py = os.path.join(pkg_dir, "__init__.py")
        if not os.path.exists(init_py):
            with open(init_py, "w", encoding="utf-8") as file:
                file.write("# Auto-generated by FluxaVision\npass\n")

        netsdk_mod = None
        netsdk_file = None
        for name in ("netsdk.pyd", "netsdk.so"):
            candidate = os.path.join(pkg_dir, name)
            if os.path.exists(candidate):
                netsdk_file = candidate
                break

        if netsdk_file:
            spec = importlib.util.spec_from_file_location("NetSDK.netsdk", netsdk_file)
            netsdk_mod = importlib.util.module_from_spec(spec)
            sys.modules["NetSDK.netsdk"] = netsdk_mod
            sys.modules["netsdk"] = netsdk_mod
            spec.loader.exec_module(netsdk_mod)
            logger.debug("NetSDK: netsdk C扩展已加载")
        else:
            logger.debug("NetSDK: 未找到 netsdk C扩展文件")

        callback_file = os.path.join(pkg_dir, "SDK_Callback.py")
        callback_mod = None
        if os.path.exists(callback_file):
            spec = importlib.util.spec_from_file_location("NetSDK.SDK_Callback", callback_file)
            callback_mod = importlib.util.module_from_spec(spec)
            sys.modules["NetSDK.SDK_Callback"] = callback_mod
            spec.loader.exec_module(callback_mod)
            logger.debug("NetSDK: SDK_Callback 已加载")
        else:
            logger.debug(f"NetSDK: 未找到 SDK_Callback.py ({callback_file})")

        struct_file = os.path.join(pkg_dir, "SDK_Struct.py")
        struct_mod = None
        if os.path.exists(struct_file):
            spec = importlib.util.spec_from_file_location("NetSDK.SDK_Struct", struct_file)
            struct_mod = importlib.util.module_from_spec(spec)
            sys.modules["NetSDK.SDK_Struct"] = struct_mod
            spec.loader.exec_module(struct_mod)
            logger.debug("NetSDK: SDK_Struct 已加载")
        else:
            logger.debug(f"NetSDK: 未找到 SDK_Struct.py ({struct_file})")

        sdk_py = os.path.join(pkg_dir, "NetSDK.py")
        if not os.path.exists(sdk_py):
            raise ImportError(f"NetSDK.py not found at {sdk_py}")

        sdk_mod = types.ModuleType("NetSDK.NetSDK")
        sdk_mod.__package__ = "NetSDK"
        sdk_mod.__file__ = sdk_py
        sdk_mod.NetSDK = sdk_mod

        for dep_mod, dep_name in (
            (netsdk_mod, "netsdk"),
            (callback_mod, "SDK_Callback"),
            (struct_mod, "SDK_Struct"),
        ):
            if dep_mod is None:
                continue
            sdk_mod.__dict__[dep_name] = dep_mod
            for attr in dir(dep_mod):
                if not attr.startswith("_"):
                    sdk_mod.__dict__[attr] = getattr(dep_mod, attr)

        sys.modules["NetSDK.NetSDK"] = sdk_mod

        try:
            import NetSDK as parent_pkg
            parent_pkg.NetSDK = sdk_mod
            if netsdk_mod:
                parent_pkg.netsdk = netsdk_mod
            if callback_mod:
                parent_pkg.SDK_Callback = callback_mod
            if struct_mod:
                parent_pkg.SDK_Struct = struct_mod
        except Exception:
            pass

        with open(sdk_py, "r", encoding="utf-8") as file:
            code = file.read()
        exec(compile(code, sdk_py, "exec"), sdk_mod.__dict__)

        return sdk_mod, netsdk_mod, callback_mod, struct_mod

    def _safe_getattr(mod, name, fallback_mods=None):
        value = getattr(mod, name, None)
        if value is not None:
            return value
        if fallback_mods:
            for fb in fallback_mods:
                value = getattr(fb, name, None)
                if value is not None:
                    return value
        raise AttributeError(f"无法找到 NetSDK 符号: {name}")

    _net_sdk_mod, _netsdk_c_ext, _callback_mod, _struct_mod = _load_netsdk()
    _fallback = [mod for mod in (_netsdk_c_ext, _callback_mod, _struct_mod) if mod is not None]

    NetClient = _safe_getattr(_net_sdk_mod, "NetClient", _fallback)
    fDisConnect = _safe_getattr(_net_sdk_mod, "fDisConnect", _fallback)
    fHaveReConnect = _safe_getattr(_net_sdk_mod, "fHaveReConnect", _fallback)
    fAnalyzerDataCallBack = _safe_getattr(_callback_mod, "fAnalyzerDataCallBack", _fallback)
    NET_IN_ATTACH_VIDEOSTAT_SUM = _safe_getattr(_struct_mod, "NET_IN_ATTACH_VIDEOSTAT_SUM", _fallback)
    NET_OUT_ATTACH_VIDEOSTAT_SUM = _safe_getattr(_struct_mod, "NET_OUT_ATTACH_VIDEOSTAT_SUM", _fallback)
    NET_A_DEV_EVENT_NUMBERSTAT_INFO = _safe_getattr(_struct_mod, "NET_A_DEV_EVENT_NUMBERSTAT_INFO", _fallback)
    NET_IN_FINDNUMBERSTAT = _safe_getattr(_struct_mod, "NET_IN_FINDNUMBERSTAT", _fallback)
    NET_OUT_FINDNUMBERSTAT = _safe_getattr(_struct_mod, "NET_OUT_FINDNUMBERSTAT", _fallback)
    NET_IN_DOFINDNUMBERSTAT = _safe_getattr(_struct_mod, "NET_IN_DOFINDNUMBERSTAT", _fallback)
    NET_OUT_DOFINDNUMBERSTAT = _safe_getattr(_struct_mod, "NET_OUT_DOFINDNUMBERSTAT", _fallback)
    NET_A_NUMBERSTAT = _safe_getattr(_struct_mod, "NET_A_NUMBERSTAT", _fallback)
    NET_TIME = _safe_getattr(_struct_mod, "NET_TIME", _fallback)
    EM_EVENT_IVS_TYPE = _safe_getattr(_net_sdk_mod, "EM_EVENT_IVS_TYPE", _fallback)

    _SDK_AVAILABLE = True
    logger.info("大华 NetSDK 加载成功（importlib 模式）")
except ImportError as exc:
    logger.warning(f"大华 NetSDK 未安装，客流采集功能不可用（仅支持 Windows）: {exc}")
except Exception as exc:
    logger.warning(f"大华 NetSDK 加载失败: {exc}\n{traceback.format_exc()}")


class DeviceConnection:
    """保存单个设备的连接状态。"""

    def __init__(
        self,
        device_id: str,
        ip: str,
        port: int,
        username: str,
        password: str,
        channel: int = 0,
    ):
        self.device_id = device_id
        self.ip = ip
        self.port = port
        self.username = username
        self.password = password
        self.channel = channel

        self.login_id: int = 0
        self.attach_handle: int = 0
        self.attach_mode: str = ""

        self.state: str = "disconnected"
        self.reconnect_thread: Optional[threading.Thread] = None
        self.poll_thread: Optional[threading.Thread] = None
        self.stop_event = threading.Event()
        self.reconnect_attempts: int = 0
        self.last_error: str = ""
        self.last_connected_at: Optional[datetime] = None
        self.last_stat_time: Optional[datetime] = None
        self.stat_callback_ref = None


class DahuaTrafficCollector:
    """大华 SDK 客流采集器。"""

    INITIAL_BACKOFF = 3
    MAX_BACKOFF = 30
    BACKOFF_MULTIPLIER = 2
    POLL_INTERVAL = 5

    def __init__(self):
        self._initialized = False
        self._devices = {}
        self._login_id_map = {}
        self._ip_port_map = {}
        self._last_stat = {}
        self._lock = threading.Lock()
        self._sdk = None

    @property
    def available(self) -> bool:
        return _SDK_AVAILABLE

    def start(
        self,
        device_id: str,
        ip: str,
        port: int,
        username: str,
        password: str,
        channel: int = 0,
    ) -> bool:
        """启动指定设备的客流采集。"""
        if not self.available:
            logger.error(f"[{device_id}] SDK 不可用，无法启动采集")
            return False

        self._ensure_init()

        with self._lock:
            if device_id in self._devices:
                conn = self._devices[device_id]
                if conn.state in ("connected", "connecting"):
                    logger.info(f"[{device_id}] 已在采集中（状态={conn.state}），跳过")
                    return True

                conn.stop_event.set()
                if conn.reconnect_thread and conn.reconnect_thread.is_alive():
                    conn.reconnect_thread.join(timeout=2)
                self._cleanup_connection(conn)

            conn = DeviceConnection(device_id, ip, port, username, password, channel)
            self._devices[device_id] = conn
            self._ip_port_map[(ip, port)] = device_id

        thread = threading.Thread(
            target=self._connect_device,
            args=(device_id,),
            daemon=True,
            name=f"dahua-{device_id[:8]}",
        )
        thread.start()
        logger.info(f"[{device_id}] 已提交采集任务: {ip}:{port} (通道={channel})")
        return True

    def stop(self, device_id: str) -> bool:
        """停止指定设备的客流采集。"""
        with self._lock:
            conn = self._devices.pop(device_id, None)
            if not conn:
                logger.info(f"[{device_id}] 未在采集中")
                return True

            conn.state = "stopped"
            conn.stop_event.set()
            self._login_id_map.pop(conn.login_id, None)
            self._ip_port_map.pop((conn.ip, conn.port), None)

            login_id = conn.login_id
            attach_handle = conn.attach_handle
            attach_mode = conn.attach_mode

        if conn.reconnect_thread and conn.reconnect_thread.is_alive():
            conn.reconnect_thread.join(timeout=3)

        if self._initialized and self._sdk:
            if attach_handle:
                try:
                    if attach_mode == "event":
                        self._sdk.StopLoadPic(attach_handle)
                    else:
                        self._sdk.DetachVideoStatSummary(attach_handle)
                    logger.info(f"[{device_id}] 已取消客流订阅 (mode={attach_mode})")
                except Exception as exc:
                    logger.error(f"[{device_id}] 取消订阅失败: {exc}")

            if login_id:
                try:
                    self._sdk.Logout(login_id)
                    logger.info(f"[{device_id}] 已注销设备登录 (login_id={login_id})")
                except Exception as exc:
                    logger.error(f"[{device_id}] 注销失败: {exc}")

        conn.stat_callback_ref = None
        self._last_stat.pop(device_id, None)
        logger.info(f"[{device_id}] 客流采集已停止，资源已释放")
        return True

    def stop_all(self):
        """停止所有设备采集。"""
        device_ids = list(self._devices.keys())
        for device_id in device_ids:
            self.stop(device_id)

        if self._initialized and self._sdk:
            try:
                self._sdk.Cleanup()
            except Exception:
                pass
            self._initialized = False
            self._login_id_map.clear()
            self._ip_port_map.clear()
            logger.info("大华 SDK 已清理，所有设备采集已停止")

    def start_all_from_db(self):
        """从数据库自动加载大华设备并启动采集。"""
        if not self.available:
            logger.warning("SDK 不可用，跳过自动启动设备采集")
            return

        try:
            from database import get_session_factory
            from models import Device

            SessionFactory = get_session_factory()
            with SessionFactory() as session:
                devices = session.query(Device).filter(Device.model == "大华").all()

            if not devices:
                logger.info("没有需要自动启动的大华设备")
                return

            logger.info(f"自动启动 {len(devices)} 台大华设备客流采集...")
            for device in devices:
                self.start(
                    device_id=device.id,
                    ip=device.ip,
                    port=device.sdkPort or 37777,
                    username=device.username or "admin",
                    password=device.password or "",
                    channel=device.channel or 0,
                )
        except Exception as exc:
            logger.error(f"自动启动设备采集失败: {exc}", exc_info=True)

    def get_realtime_data(self, device_id: str) -> dict:
        with self._lock:
            conn = self._devices.get(device_id)
            collecting = conn is not None
            state = conn.state if conn else "unknown"
            stat = self._last_stat.get(device_id, {})

        return {
            "deviceId": device_id,
            "enteredToday": stat.get("entered_today", 0),
            "exitedToday": stat.get("exited_today", 0),
            "insideNow": stat.get("inside", 0),
            "lastUpdate": stat.get("time", datetime.min).isoformat() if stat.get("time") else None,
            "collecting": collecting,
            "state": state,
        }

    def get_all_realtime_data(self) -> list:
        return [self.get_realtime_data(device_id) for device_id in list(self._devices.keys())]

    def get_device_collector_state(self, device_id: str) -> dict:
        with self._lock:
            conn = self._devices.get(device_id)
            if not conn:
                return {"collecting": False, "state": "not_started"}

        return {
            "collecting": True,
            "state": conn.state,
            "reconnectAttempts": conn.reconnect_attempts,
            "lastError": conn.last_error,
            "lastConnectedAt": conn.last_connected_at.isoformat() if conn.last_connected_at else None,
            "lastStatTime": conn.last_stat_time.isoformat() if conn.last_stat_time else None,
        }

    def _ensure_init(self):
        """确保 SDK 已初始化。"""
        if not _SDK_AVAILABLE:
            raise RuntimeError("大华 NetSDK 未安装，仅支持 Windows 环境")
        if self._initialized:
            return

        self._sdk = NetClient()
        disconnect_cb = fDisConnect(self._on_disconnect)
        reconnect_cb = fHaveReConnect(self._on_reconnect)
        self._sdk.InitEx(disconnect_cb)
        self._sdk.SetAutoReconnect(reconnect_cb)
        self._initialized = True
        logger.info("大华 SDK 初始化完成（已启用自动重连）")

    def _sdk_error_text(self) -> str:
        err_code = self._sdk.GetLastError() if hasattr(self._sdk, "GetLastError") else None
        err_msg = self._sdk.GetLastErrorMessage() if hasattr(self._sdk, "GetLastErrorMessage") else ""
        return f"err={err_code}, msg={err_msg or 'unknown'}"

    def _connect_device(self, device_id: str):
        """执行设备登录并建立客流采集。"""
        with self._lock:
            conn = self._devices.get(device_id)
            if not conn or conn.state == "stopped":
                return

        conn.state = "connecting"
        self._update_device_status(device_id, "warning")
        logger.info(
            f"[{device_id}] 开始连接设备: ip={conn.ip}, port={conn.port}, channel={conn.channel}, "
            f"user={conn.username}, rule=NumberStat1"
        )

        try:
            login_id, _, error_msg = self._sdk.LoginEx2(
                conn.ip, conn.port, conn.username, conn.password
            )
            if not login_id or login_id == 0:
                raise RuntimeError(f"登录失败: {error_msg or '未知错误'}")

            with self._lock:
                if conn.state == "stopped":
                    self._sdk.Logout(login_id)
                    return
                conn.login_id = login_id
                self._login_id_map[login_id] = device_id

            logger.info(f"[{device_id}] 登录设备成功: {conn.ip}:{conn.port} (login_id={login_id})")

            attach_handle = self._attach_video_stat(conn)
            if not attach_handle:
                logger.warning(f"[{device_id}] 客流订阅未建立，改用主动查询模式继续采集")

            with self._lock:
                if conn.state == "stopped":
                    if attach_handle:
                        if conn.attach_mode == "event":
                            self._sdk.StopLoadPic(attach_handle)
                        else:
                            self._sdk.DetachVideoStatSummary(attach_handle)
                    self._sdk.Logout(login_id)
                    return

                conn.attach_handle = attach_handle or 0
                conn.state = "connected"
                conn.reconnect_attempts = 0
                conn.last_error = ""
                conn.last_connected_at = datetime.now()

            self._update_device_status(device_id, "online")
            self._ensure_polling_thread(conn)
            logger.info(
                f"[{device_id}] 客流采集已启动: mode={conn.attach_mode or 'poll'}, "
                f"attach_handle={conn.attach_handle}, channel={conn.channel}"
            )
        except Exception as exc:
            conn.last_error = str(exc)
            logger.error(f"[{device_id}] 连接失败: {exc}")
            if conn.state != "stopped":
                self._start_reconnect(device_id)

    def _start_reconnect(self, device_id: str):
        """启动重连循环。"""
        with self._lock:
            conn = self._devices.get(device_id)
            if not conn or conn.state == "stopped":
                return
            if conn.state == "connected":
                return

            conn.stop_event.set()
            if conn.reconnect_thread and conn.reconnect_thread.is_alive():
                conn.reconnect_thread.join(timeout=2)

            conn.stop_event.clear()
            conn.state = "reconnecting"
            conn.reconnect_attempts += 1
            logger.info(f"[{device_id}] 启动重连流程 (第{conn.reconnect_attempts}次, {conn.ip}:{conn.port})")

        self._update_device_status(device_id, "warning")
        thread = threading.Thread(
            target=self._reconnect_loop,
            args=(device_id,),
            daemon=True,
            name=f"reconnect-{device_id[:8]}",
        )
        thread.start()
        conn.reconnect_thread = thread

    def _reconnect_loop(self, device_id: str):
        """后台重连设备。"""
        with self._lock:
            conn = self._devices.get(device_id)
            if not conn:
                return
            stop_event = conn.stop_event
            self._cleanup_connection(conn)

        backoff = self.INITIAL_BACKOFF
        while not stop_event.is_set():
            with self._lock:
                if conn.state in ("connected", "stopped") or device_id not in self._devices:
                    return

            logger.info(f"[{device_id}] {backoff}s 后尝试重连 {conn.ip}:{conn.port}")
            if stop_event.wait(backoff):
                return

            with self._lock:
                if conn.state in ("connected", "stopped") or device_id not in self._devices:
                    return

            try:
                login_id, _, error_msg = self._sdk.LoginEx2(
                    conn.ip, conn.port, conn.username, conn.password
                )
                if not login_id or login_id == 0:
                    raise RuntimeError(f"登录失败: {error_msg or '连接被拒绝'}")

                with self._lock:
                    if conn.state == "stopped" or device_id not in self._devices:
                        self._sdk.Logout(login_id)
                        return
                    conn.login_id = login_id
                    self._login_id_map[login_id] = device_id

                logger.info(f"[{device_id}] 重连登录成功 (login_id={login_id})")

                attach_handle = self._attach_video_stat(conn)
                if not attach_handle:
                    logger.warning(f"[{device_id}] 重连后订阅失败，改用主动查询模式继续采集")

                with self._lock:
                    if conn.state == "stopped" or device_id not in self._devices:
                        if attach_handle:
                            if conn.attach_mode == "event":
                                self._sdk.StopLoadPic(attach_handle)
                            else:
                                self._sdk.DetachVideoStatSummary(attach_handle)
                        self._sdk.Logout(login_id)
                        return

                    conn.attach_handle = attach_handle or 0
                    conn.state = "connected"
                    conn.reconnect_attempts = 0
                    conn.last_error = ""
                    conn.last_connected_at = datetime.now()

                self._update_device_status(device_id, "online")
                self._ensure_polling_thread(conn)
                logger.info(
                    f"[{device_id}] 断线重连成功: mode={conn.attach_mode or 'poll'}, "
                    f"attach_handle={conn.attach_handle}"
                )
                return
            except Exception as exc:
                conn.last_error = str(exc)
                conn.reconnect_attempts += 1
                logger.warning(f"[{device_id}] 重连失败 (第{conn.reconnect_attempts}次): {exc}")

            backoff = min(backoff * self.BACKOFF_MULTIPLIER, self.MAX_BACKOFF)

        logger.info(f"[{device_id}] 重连循环已退出（设备已停止）")

    def _cleanup_connection(self, conn: DeviceConnection):
        """清理登录和订阅句柄。"""
        if conn.login_id:
            self._login_id_map.pop(conn.login_id, None)
            conn.login_id = 0
        conn.attach_handle = 0
        conn.attach_mode = ""
        conn.stat_callback_ref = None

    def _on_disconnect(self, lLoginID, ip, port, user_data):
        """SDK 断线回调。"""
        with self._lock:
            device_id = self._login_id_map.get(lLoginID) or self._ip_port_map.get((ip, port))
            if not device_id:
                logger.warning(f"未知设备断线: login_id={lLoginID}, ip={ip}, port={port}")
                return

            conn = self._devices.get(device_id)
            if not conn or conn.state == "stopped":
                return

            conn.state = "disconnected"
            conn.attach_handle = 0
            logger.warning(f"[{device_id}] 设备断线: ip={ip}, port={port}, login_id={lLoginID}")

        self._update_device_status(device_id, "offline")
        self._start_reconnect(device_id)

    def _on_reconnect(self, lLoginID, ip, port, user_data):
        """SDK 自动重连成功回调。"""
        with self._lock:
            device_id = self._login_id_map.get(lLoginID) or self._ip_port_map.get((ip, port))
            if not device_id:
                logger.info(f"未知设备 SDK 重连: login_id={lLoginID}, ip={ip}, port={port}")
                return

            conn = self._devices.get(device_id)
            if not conn or conn.state == "stopped":
                return
            if conn.state == "connected":
                logger.info(f"[{device_id}] SDK 重连回调到达，但设备已经处于连接状态")
                return

            logger.info(
                f"[{device_id}] SDK 自动重连成功: ip={ip}, port={port}, "
                f"旧login_id={conn.login_id}, 新login_id={lLoginID}"
            )

            if conn.login_id and conn.login_id != lLoginID:
                self._login_id_map.pop(conn.login_id, None)

            conn.login_id = lLoginID
            self._login_id_map[lLoginID] = device_id
            conn.state = "connected"
            conn.reconnect_attempts = 0
            conn.last_error = ""
            conn.last_connected_at = datetime.now()
            conn.stop_event.set()

        try:
            attach_handle = self._attach_video_stat(conn)
            if not attach_handle:
                logger.warning(f"[{device_id}] SDK 重连后订阅失败，改用主动查询模式继续采集")

            with self._lock:
                if conn.state == "stopped":
                    return
                conn.attach_handle = attach_handle or 0

            self._update_device_status(device_id, "online")
            self._ensure_polling_thread(conn)
            logger.info(
                f"[{device_id}] SDK 重连后采集恢复成功: mode={conn.attach_mode or 'poll'}, "
                f"attach_handle={conn.attach_handle}"
            )
        except Exception as exc:
            logger.error(f"[{device_id}] SDK 重连后恢复采集失败: {exc}")
            conn.last_error = f"重连后恢复采集失败: {exc}"
            conn.state = "reconnecting"
            conn.stop_event.clear()
            self._start_reconnect(device_id)

    def _attach_video_stat(self, conn: DeviceConnection) -> Optional[int]:
        """优先使用客流摘要订阅，失败后切换到事件订阅。"""
        device_id = conn.device_id
        callback_type = dict(NET_IN_ATTACH_VIDEOSTAT_SUM._fields_)["cbVideoStatSum"]

        def stat_callback(lAttachHandle, pStatBuf, dwBufLen, dwUser):
            try:
                stat = pStatBuf.contents if pStatBuf else None
                if stat:
                    self._on_stat_update(device_id, stat)
            except Exception as exc:
                logger.error(f"[{device_id}] 处理客流摘要回调失败: {exc}")

        callback_wrapper = callback_type(stat_callback)
        conn.stat_callback_ref = callback_wrapper

        for subclass_id in ("NumberStat1", "NumberStat"):
            try:
                in_param = NET_IN_ATTACH_VIDEOSTAT_SUM()
                in_param.dwSize = ctypes.sizeof(NET_IN_ATTACH_VIDEOSTAT_SUM)
                in_param.nChannel = conn.channel
                in_param.cbVideoStatSum = callback_wrapper
                in_param.dwUser = 0
                in_param.szSubClassID = f"{subclass_id}\x00".encode("ascii")

                out_param = NET_OUT_ATTACH_VIDEOSTAT_SUM()
                out_param.dwSize = ctypes.sizeof(NET_OUT_ATTACH_VIDEOSTAT_SUM)

                logger.info(
                    f"[{device_id}] 尝试 AttachVideoStatSummary: channel={conn.channel}, "
                    f"subclass={subclass_id}, login_id={conn.login_id}"
                )
                handle = self._sdk.AttachVideoStatSummary(conn.login_id, in_param, out_param, 5000)
                if handle:
                    conn.attach_mode = "video_stat"
                    logger.info(
                        f"[{device_id}] AttachVideoStatSummary 成功: handle={handle}, subclass={subclass_id}"
                    )
                    return handle

                logger.warning(
                    f"[{device_id}] AttachVideoStatSummary 失败: subclass={subclass_id}, {self._sdk_error_text()}"
                )
            except Exception as exc:
                logger.error(f"[{device_id}] AttachVideoStatSummary 异常: subclass={subclass_id}, error={exc}")

        return self._attach_number_stat_event(conn)

    def _attach_number_stat_event(self, conn: DeviceConnection) -> Optional[int]:
        """使用 NUMBERSTAT 智能事件回调作为第二条采集链路。"""
        device_id = conn.device_id

        def analyzer_callback(
            lAnalyzerHandle,
            dwAlarmType,
            pAlarmInfo,
            pBuffer,
            dwBufSize,
            dwUser,
            nSequence,
            reserved,
        ):
            try:
                if int(dwAlarmType) != int(EM_EVENT_IVS_TYPE.NUMBERSTAT):
                    return
                if not pAlarmInfo:
                    return
                alarm = ctypes.cast(
                    pAlarmInfo,
                    ctypes.POINTER(NET_A_DEV_EVENT_NUMBERSTAT_INFO),
                ).contents
                self._on_number_stat_event(device_id, alarm)
            except Exception as exc:
                logger.error(f"[{device_id}] 处理 NUMBERSTAT 事件回调失败: {exc}")

        callback_wrapper = fAnalyzerDataCallBack(analyzer_callback)
        conn.stat_callback_ref = callback_wrapper

        try:
            logger.info(
                f"[{device_id}] 尝试 NUMBERSTAT 事件订阅: channel={conn.channel}, login_id={conn.login_id}"
            )
            handle = self._sdk.RealLoadPictureEx(
                conn.login_id,
                conn.channel,
                int(EM_EVENT_IVS_TYPE.NUMBERSTAT),
                0,
                callback_wrapper,
                0,
                None,
            )
            if handle:
                conn.attach_mode = "event"
                logger.info(f"[{device_id}] NUMBERSTAT 事件订阅成功: handle={handle}")
                return handle

            logger.error(f"[{device_id}] NUMBERSTAT 事件订阅失败: {self._sdk_error_text()}")
            return None
        except Exception as exc:
            logger.error(f"[{device_id}] NUMBERSTAT 事件订阅异常: {exc}")
            return None

    def _on_number_stat_event(self, device_id: str, alarm):
        """处理 NUMBERSTAT 事件回调。"""
        try:
            t = alarm.UTC
            stat_time = datetime(t.dwYear, t.dwMonth, t.dwDay, t.dwHour, t.dwMinute, t.dwSecond)
            entered = max(0, int(alarm.nEnteredNumber or 0))
            exited = max(0, int(alarm.nExitedNumber or 0))
            inside = max(0, int(alarm.nNumber or 0))
            passed = max(0, int(alarm.nPassedNumber or 0))
            rule_name = bytes(alarm.szName).split(b"\x00", 1)[0].decode("utf-8", errors="ignore")

            logger.info(
                f"[{device_id}] 收到 NUMBERSTAT 事件: name={rule_name or '-'}, "
                f"channel={alarm.nChannelID}, entered={entered}, exited={exited}, passed={passed}, inside={inside}, "
                f"action={int(alarm.bEventAction)}"
            )

            last = self._last_stat.get(device_id, {})
            self._apply_cumulative_stat(
                device_id=device_id,
                entered_today=int(last.get("entered_today", 0)) + entered,
                exited_today=int(last.get("exited_today", 0)) + exited,
                inside_now=inside,
                stat_time=stat_time,
            )
        except Exception as exc:
            logger.error(f"[{device_id}] 处理 NUMBERSTAT 事件失败: {exc}")

    def _on_stat_update(self, device_id: str, stat):
        """处理 AttachVideoStatSummary 的统计回调。"""
        try:
            t = stat.stuTime
            stat_time = datetime(t.dwYear, t.dwMonth, t.dwDay, t.dwHour, t.dwMinute, t.dwSecond)

            self._apply_cumulative_stat(
                device_id=device_id,
                entered_today=int(stat.stuEnteredSubtotal.nToday or 0),
                exited_today=int(stat.stuExitedSubtotal.nToday or 0),
                inside_now=int(stat.nInsidePeopleNum or 0),
                stat_time=stat_time,
                entered_hour=int(stat.stuEnteredSubtotal.nHour or 0),
                exited_hour=int(stat.stuExitedSubtotal.nHour or 0),
            )
        except Exception as exc:
            logger.error(f"[{device_id}] 处理客流摘要数据异常: {exc}")

    def _save_traffic_record(self, device_id: str, date_str: str, hour: int, count_in: int, count_out: int):
        """将小时级客流增量写入数据库。"""
        try:
            from database import get_session_factory
            from models import TrafficRecord

            SessionFactory = get_session_factory()
            with SessionFactory() as session:
                record = session.query(TrafficRecord).filter_by(
                    deviceId=device_id,
                    date=date_str,
                    hour=hour,
                ).first()

                if record:
                    record.countIn = (record.countIn or 0) + count_in
                    record.countOut = (record.countOut or 0) + count_out
                    record.updatedAt = datetime.utcnow()
                else:
                    record = TrafficRecord(
                        deviceId=device_id,
                        date=date_str,
                        hour=hour,
                        countIn=count_in,
                        countOut=count_out,
                    )
                    session.add(record)

                session.commit()

            logger.info(
                f"[{device_id}] 已写入客流增量: date={date_str}, hour={hour}, in={count_in}, out={count_out}"
            )
        except Exception as exc:
            logger.error(f"[{device_id}] 保存客流记录失败: {exc}")

    def _ensure_polling_thread(self, conn: DeviceConnection):
        """确保主动查询线程已启动。"""
        thread = conn.poll_thread
        if thread and thread.is_alive():
            return

        thread = threading.Thread(
            target=self._poll_number_stat_loop,
            args=(conn.device_id,),
            daemon=True,
            name=f"stat-poll-{conn.device_id[:8]}",
        )
        conn.poll_thread = thread
        thread.start()
        logger.info(f"[{conn.device_id}] 已启动 NumberStat 主动查询线程，轮询间隔={self.POLL_INTERVAL}s")

    def _poll_number_stat_loop(self, device_id: str):
        """周期性通过查询接口获取 NumberStat。"""
        while True:
            with self._lock:
                conn = self._devices.get(device_id)
                if not conn or conn.state == "stopped":
                    return
                login_id = conn.login_id

            if not login_id:
                time.sleep(1)
                continue

            try:
                stat_data = self._query_number_stat(conn)
                if stat_data:
                    self._apply_cumulative_stat(
                        device_id=device_id,
                        entered_today=stat_data["entered_today"],
                        exited_today=stat_data["exited_today"],
                        inside_now=stat_data["inside"],
                        stat_time=stat_data["time"],
                    )
            except Exception as exc:
                logger.warning(f"[{device_id}] 查询客流统计失败: {exc}")

            for _ in range(self.POLL_INTERVAL):
                time.sleep(1)
                with self._lock:
                    conn = self._devices.get(device_id)
                    if not conn or conn.state == "stopped":
                        return

    def _query_number_stat(self, conn: DeviceConnection) -> Optional[dict]:
        """通过 NumberStat 查询接口获取累计值。"""
        now = datetime.now()

        find_in = NET_IN_FINDNUMBERSTAT()
        find_in.dwSize = ctypes.sizeof(NET_IN_FINDNUMBERSTAT)
        find_in.nChannelID = conn.channel
        find_in.stStartTime = NET_TIME(now.year, now.month, now.day, 0, 0, 0)
        find_in.stEndTime = NET_TIME(now.year, now.month, now.day, 23, 59, 59)
        find_in.nGranularityType = 2
        find_in.nWaittime = 5000
        find_in.emRuleType = 1

        find_out = NET_OUT_FINDNUMBERSTAT()
        find_out.dwSize = ctypes.sizeof(NET_OUT_FINDNUMBERSTAT)

        logger.debug(
            f"[{conn.device_id}] 开始 NumberStat 查询: channel={conn.channel}, login_id={conn.login_id}, "
            f"start={now.strftime('%Y-%m-%d 00:00:00')}, end={now.strftime('%Y-%m-%d 23:59:59')}"
        )

        find_handle = self._sdk.StartFindNumberStat(conn.login_id, find_in, find_out)
        if not find_handle:
            raise RuntimeError(f"StartFindNumberStat 失败: {self._sdk_error_text()}")

        try:
            fetch_count = 32
            stat_buffer = (NET_A_NUMBERSTAT * fetch_count)()
            item_size = ctypes.sizeof(NET_A_NUMBERSTAT)
            for item in stat_buffer:
                item.dwSize = item_size

            do_in = NET_IN_DOFINDNUMBERSTAT()
            do_in.dwSize = ctypes.sizeof(NET_IN_DOFINDNUMBERSTAT)
            do_in.nBeginNumber = 0
            do_in.nCount = fetch_count
            do_in.nWaittime = 5000

            do_out = NET_OUT_DOFINDNUMBERSTAT()
            do_out.dwSize = ctypes.sizeof(NET_OUT_DOFINDNUMBERSTAT)
            do_out.pstuNumberStat = ctypes.cast(stat_buffer, ctypes.POINTER(NET_A_NUMBERSTAT))
            do_out.nBufferLen = ctypes.sizeof(stat_buffer)

            ok = self._sdk.DoFindNumberStat(find_handle, do_in, do_out)
            if not ok:
                raise RuntimeError(f"DoFindNumberStat 失败: {self._sdk_error_text()}")

            count = max(0, min(int(do_out.nCount or 0), fetch_count))
            logger.info(
                f"[{conn.device_id}] NumberStat 查询返回: total={int(find_out.dwTotalCount or 0)}, "
                f"count={count}, buffer_len={do_out.nBufferLen}"
            )
            if count <= 0:
                logger.debug(f"[{conn.device_id}] NumberStat 查询成功，但当前没有返回统计记录")
                return None

            entered_today = 0
            exited_today = 0
            inside_now = 0
            real_number = 0

            for index in range(count):
                row = stat_buffer[index]
                entered_today += max(0, int(row.nEnteredSubTotal or 0))
                exited_today += max(0, int(row.nExitedSubtotal or 0))
                inside_now = max(inside_now, max(0, int(row.nInsideSubtotal or 0)))
                real_number = max(real_number, max(0, int(row.nRealNumber or 0)))

            if real_number > 0:
                inside_now = real_number

            logger.info(
                f"[{conn.device_id}] NumberStat 查询结果: 今日进={entered_today}, 今日出={exited_today}, 当前在场={inside_now}"
            )
            return {
                "entered_today": entered_today,
                "exited_today": exited_today,
                "inside": inside_now,
                "time": now,
            }
        finally:
            try:
                self._sdk.StopFindNumberStat(find_handle)
            except Exception:
                pass

    def _apply_cumulative_stat(
        self,
        device_id: str,
        entered_today: int,
        exited_today: int,
        inside_now: int,
        stat_time: datetime,
        entered_hour: Optional[int] = None,
        exited_hour: Optional[int] = None,
    ):
        """统一把累计值换算成小时增量。"""
        last = self._last_stat.get(device_id, {})
        prev_entered_today = int(last.get("entered_today", 0) or 0)
        prev_exited_today = int(last.get("exited_today", 0) or 0)
        prev_hour = int(last.get("hour", -1) or -1)
        current_hour = stat_time.hour

        delta_in = 0
        delta_out = 0
        if prev_entered_today > 0:
            delta_in = max(0, int(entered_today) - prev_entered_today)
        if prev_exited_today > 0:
            delta_out = max(0, int(exited_today) - prev_exited_today)

        if current_hour != prev_hour and prev_hour >= 0:
            if entered_hour is not None:
                delta_in = max(0, int(entered_hour))
            if exited_hour is not None:
                delta_out = max(0, int(exited_hour))

        self._last_stat[device_id] = {
            "entered_today": int(entered_today),
            "exited_today": int(exited_today),
            "inside": int(inside_now),
            "hour": current_hour,
            "time": stat_time,
            "last_log_time": last.get("last_log_time"),
        }

        with self._lock:
            conn = self._devices.get(device_id)
            if conn:
                conn.last_stat_time = stat_time

        if delta_in > 0 or delta_out > 0:
            self._save_traffic_record(
                device_id=device_id,
                date_str=stat_time.strftime("%Y-%m-%d"),
                hour=current_hour,
                count_in=delta_in,
                count_out=delta_out,
            )

        now = datetime.now()
        last_log_time = last.get("last_log_time")
        if not last_log_time or (now - last_log_time).total_seconds() > 60:
            logger.info(
                f"[{device_id}] 客流统计更新: 今日进={entered_today}, 今日出={exited_today}, "
                f"当前在场={inside_now}, 时间={stat_time.strftime('%Y-%m-%d %H:%M:%S')}"
            )
            self._last_stat[device_id]["last_log_time"] = now

    def _update_device_status(self, device_id: str, status: str):
        """同步设备状态到数据库。"""
        try:
            from database import get_session_factory
            from models import Device

            SessionFactory = get_session_factory()
            with SessionFactory() as session:
                device = session.query(Device).filter_by(id=device_id).first()
                if device and device.status != status:
                    device.status = status
                    session.commit()
                    logger.debug(f"[{device_id}] 设备状态更新: {status}")
        except Exception as exc:
            logger.error(f"[{device_id}] 更新设备状态失败: {exc}")

    def restart_device(self, device_id: str) -> bool:
        """重启指定设备的客流采集。"""
        with self._lock:
            conn = self._devices.get(device_id)
            if not conn:
                return False
            ip, port = conn.ip, conn.port
            username, password = conn.username, conn.password
            channel = conn.channel

        self.stop(device_id)
        return self.start(device_id, ip, port, username, password, channel)


dahua_collector = DahuaTrafficCollector()
